version: 0.0
os: linux
files:
  - source: mybureau-api-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu/mybureau-api/bin
  - source: start_service.sh
    destination: /home/ubuntu/mybureau-api/bin
  - source: stop_service.sh
    destination: /home/ubuntu/mybureau-api/bin
hooks:
  ApplicationStop:
    - location: stop_service.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_service.sh
      timeout: 300
      runas: root